require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MonitoringAppsController do

  # This should return the minimal set of attributes required to create a valid
  # MonitoringApp. As you add validations to MonitoringApp, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MonitoringAppsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all monitoring_apps as @monitoring_apps" do
      monitoring_app = MonitoringApp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:monitoring_apps).should eq([monitoring_app])
    end
  end

  describe "GET show" do
    it "assigns the requested monitoring_app as @monitoring_app" do
      monitoring_app = MonitoringApp.create! valid_attributes
      get :show, {:id => monitoring_app.to_param}, valid_session
      assigns(:monitoring_app).should eq(monitoring_app)
    end
  end

  describe "GET new" do
    it "assigns a new monitoring_app as @monitoring_app" do
      get :new, {}, valid_session
      assigns(:monitoring_app).should be_a_new(MonitoringApp)
    end
  end

  describe "GET edit" do
    it "assigns the requested monitoring_app as @monitoring_app" do
      monitoring_app = MonitoringApp.create! valid_attributes
      get :edit, {:id => monitoring_app.to_param}, valid_session
      assigns(:monitoring_app).should eq(monitoring_app)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MonitoringApp" do
        expect {
          post :create, {:monitoring_app => valid_attributes}, valid_session
        }.to change(MonitoringApp, :count).by(1)
      end

      it "assigns a newly created monitoring_app as @monitoring_app" do
        post :create, {:monitoring_app => valid_attributes}, valid_session
        assigns(:monitoring_app).should be_a(MonitoringApp)
        assigns(:monitoring_app).should be_persisted
      end

      it "redirects to the created monitoring_app" do
        post :create, {:monitoring_app => valid_attributes}, valid_session
        response.should redirect_to(MonitoringApp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved monitoring_app as @monitoring_app" do
        # Trigger the behavior that occurs when invalid params are submitted
        MonitoringApp.any_instance.stub(:save).and_return(false)
        post :create, {:monitoring_app => {}}, valid_session
        assigns(:monitoring_app).should be_a_new(MonitoringApp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MonitoringApp.any_instance.stub(:save).and_return(false)
        post :create, {:monitoring_app => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested monitoring_app" do
        monitoring_app = MonitoringApp.create! valid_attributes
        # Assuming there are no other monitoring_apps in the database, this
        # specifies that the MonitoringApp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MonitoringApp.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => monitoring_app.to_param, :monitoring_app => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested monitoring_app as @monitoring_app" do
        monitoring_app = MonitoringApp.create! valid_attributes
        put :update, {:id => monitoring_app.to_param, :monitoring_app => valid_attributes}, valid_session
        assigns(:monitoring_app).should eq(monitoring_app)
      end

      it "redirects to the monitoring_app" do
        monitoring_app = MonitoringApp.create! valid_attributes
        put :update, {:id => monitoring_app.to_param, :monitoring_app => valid_attributes}, valid_session
        response.should redirect_to(monitoring_app)
      end
    end

    describe "with invalid params" do
      it "assigns the monitoring_app as @monitoring_app" do
        monitoring_app = MonitoringApp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MonitoringApp.any_instance.stub(:save).and_return(false)
        put :update, {:id => monitoring_app.to_param, :monitoring_app => {}}, valid_session
        assigns(:monitoring_app).should eq(monitoring_app)
      end

      it "re-renders the 'edit' template" do
        monitoring_app = MonitoringApp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MonitoringApp.any_instance.stub(:save).and_return(false)
        put :update, {:id => monitoring_app.to_param, :monitoring_app => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested monitoring_app" do
      monitoring_app = MonitoringApp.create! valid_attributes
      expect {
        delete :destroy, {:id => monitoring_app.to_param}, valid_session
      }.to change(MonitoringApp, :count).by(-1)
    end

    it "redirects to the monitoring_apps list" do
      monitoring_app = MonitoringApp.create! valid_attributes
      delete :destroy, {:id => monitoring_app.to_param}, valid_session
      response.should redirect_to(monitoring_apps_url)
    end
  end

end
